# Generated by Django 4.2.3 on 2023-10-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_savedcarts'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcarts',
            name='token',
            field=models.IntegerField(default=1000),
        ),
    ]
