# Generated by Django 4.2.3 on 2023-10-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_savedcarts_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedcarts',
            name='token',
        ),
        migrations.AddField(
            model_name='userorder',
            name='token',
            field=models.IntegerField(default=1000),
        ),
    ]
